// Generated by gencpp from file collide_free/SetPoint.msg
// DO NOT EDIT!


#ifndef COLLIDE_FREE_MESSAGE_SETPOINT_H
#define COLLIDE_FREE_MESSAGE_SETPOINT_H

#include <ros/service_traits.h>


#include <collide_free/SetPointRequest.h>
#include <collide_free/SetPointResponse.h>


namespace collide_free
{

struct SetPoint
{

typedef SetPointRequest Request;
typedef SetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPoint
} // namespace collide_free


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::collide_free::SetPoint > {
  static const char* value()
  {
    return "1d719385decc796c11ed1d75b56878fc";
  }

  static const char* value(const ::collide_free::SetPoint&) { return value(); }
};

template<>
struct DataType< ::collide_free::SetPoint > {
  static const char* value()
  {
    return "collide_free/SetPoint";
  }

  static const char* value(const ::collide_free::SetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::collide_free::SetPointRequest> should match
// service_traits::MD5Sum< ::collide_free::SetPoint >
template<>
struct MD5Sum< ::collide_free::SetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::collide_free::SetPoint >::value();
  }
  static const char* value(const ::collide_free::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::collide_free::SetPointRequest> should match
// service_traits::DataType< ::collide_free::SetPoint >
template<>
struct DataType< ::collide_free::SetPointRequest>
{
  static const char* value()
  {
    return DataType< ::collide_free::SetPoint >::value();
  }
  static const char* value(const ::collide_free::SetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::collide_free::SetPointResponse> should match
// service_traits::MD5Sum< ::collide_free::SetPoint >
template<>
struct MD5Sum< ::collide_free::SetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::collide_free::SetPoint >::value();
  }
  static const char* value(const ::collide_free::SetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::collide_free::SetPointResponse> should match
// service_traits::DataType< ::collide_free::SetPoint >
template<>
struct DataType< ::collide_free::SetPointResponse>
{
  static const char* value()
  {
    return DataType< ::collide_free::SetPoint >::value();
  }
  static const char* value(const ::collide_free::SetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLIDE_FREE_MESSAGE_SETPOINT_H
