// Generated by gencpp from file collide_free/SetPointRequest.msg
// DO NOT EDIT!


#ifndef COLLIDE_FREE_MESSAGE_SETPOINTREQUEST_H
#define COLLIDE_FREE_MESSAGE_SETPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace collide_free
{
template <class ContainerAllocator>
struct SetPointRequest_
{
  typedef SetPointRequest_<ContainerAllocator> Type;

  SetPointRequest_()
    : pose()  {
    }
  SetPointRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::collide_free::SetPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collide_free::SetPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPointRequest_

typedef ::collide_free::SetPointRequest_<std::allocator<void> > SetPointRequest;

typedef boost::shared_ptr< ::collide_free::SetPointRequest > SetPointRequestPtr;
typedef boost::shared_ptr< ::collide_free::SetPointRequest const> SetPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collide_free::SetPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collide_free::SetPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::collide_free::SetPointRequest_<ContainerAllocator1> & lhs, const ::collide_free::SetPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::collide_free::SetPointRequest_<ContainerAllocator1> & lhs, const ::collide_free::SetPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace collide_free

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::collide_free::SetPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collide_free::SetPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collide_free::SetPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collide_free::SetPointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collide_free::SetPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collide_free::SetPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collide_free::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76249fb45cba333e6a82c7f91cfe1879";
  }

  static const char* value(const ::collide_free::SetPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76249fb45cba333eULL;
  static const uint64_t static_value2 = 0x6a82c7f91cfe1879ULL;
};

template<class ContainerAllocator>
struct DataType< ::collide_free::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collide_free/SetPointRequest";
  }

  static const char* value(const ::collide_free::SetPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collide_free::SetPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] pose\n"
;
  }

  static const char* value(const ::collide_free::SetPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collide_free::SetPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collide_free::SetPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collide_free::SetPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLIDE_FREE_MESSAGE_SETPOINTREQUEST_H
