// Generated by gencpp from file collide_free/SetPointResponse.msg
// DO NOT EDIT!


#ifndef COLLIDE_FREE_MESSAGE_SETPOINTRESPONSE_H
#define COLLIDE_FREE_MESSAGE_SETPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace collide_free
{
template <class ContainerAllocator>
struct SetPointResponse_
{
  typedef SetPointResponse_<ContainerAllocator> Type;

  SetPointResponse_()
    : wm()
    , wh()
    , t()  {
    }
  SetPointResponse_(const ContainerAllocator& _alloc)
    : wm(_alloc)
    , wh(_alloc)
    , t(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _wm_type;
  _wm_type wm;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _wh_type;
  _wh_type wh;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _t_type;
  _t_type t;





  typedef boost::shared_ptr< ::collide_free::SetPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collide_free::SetPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetPointResponse_

typedef ::collide_free::SetPointResponse_<std::allocator<void> > SetPointResponse;

typedef boost::shared_ptr< ::collide_free::SetPointResponse > SetPointResponsePtr;
typedef boost::shared_ptr< ::collide_free::SetPointResponse const> SetPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collide_free::SetPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collide_free::SetPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::collide_free::SetPointResponse_<ContainerAllocator1> & lhs, const ::collide_free::SetPointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.wm == rhs.wm &&
    lhs.wh == rhs.wh &&
    lhs.t == rhs.t;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::collide_free::SetPointResponse_<ContainerAllocator1> & lhs, const ::collide_free::SetPointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace collide_free

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::collide_free::SetPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collide_free::SetPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collide_free::SetPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collide_free::SetPointResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collide_free::SetPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collide_free::SetPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collide_free::SetPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "217099dae91577c60de7e73dd2aa8c7c";
  }

  static const char* value(const ::collide_free::SetPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x217099dae91577c6ULL;
  static const uint64_t static_value2 = 0x0de7e73dd2aa8c7cULL;
};

template<class ContainerAllocator>
struct DataType< ::collide_free::SetPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collide_free/SetPointResponse";
  }

  static const char* value(const ::collide_free::SetPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collide_free::SetPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] wm\n"
"float64[] wh\n"
"float64[] t\n"
"\n"
;
  }

  static const char* value(const ::collide_free::SetPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collide_free::SetPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wm);
      stream.next(m.wh);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collide_free::SetPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collide_free::SetPointResponse_<ContainerAllocator>& v)
  {
    s << indent << "wm[]" << std::endl;
    for (size_t i = 0; i < v.wm.size(); ++i)
    {
      s << indent << "  wm[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.wm[i]);
    }
    s << indent << "wh[]" << std::endl;
    for (size_t i = 0; i < v.wh.size(); ++i)
    {
      s << indent << "  wh[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.wh[i]);
    }
    s << indent << "t[]" << std::endl;
    for (size_t i = 0; i < v.t.size(); ++i)
    {
      s << indent << "  t[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.t[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLIDE_FREE_MESSAGE_SETPOINTRESPONSE_H
